Create 11.2.5.37pm
main.cpp:5:7: error: expected '(' for function-style cast or type construction
  int count = 0;
  ~~~ ^
main.cpp:6:3: error: expected unqualified-id
  for (int i = 0; i < arraySize; i++) {
  ^
main.cpp:16:14: error: use of undeclared identifier 'arraySize'
if (count == arraySize) {
             ^
main.cpp:18:12: error: expected ';' after return statement
  return -1
           ^
           ;
main.cpp:20:9: error: address of overloaded function 'count' does not match required type 'int'
 return count;
        ^~~~~
/root/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__algorithm/count.h:25:5: note: candidate template ignored: could not match 'typename iterator_traits<_InputIterator>::difference_type (_InputIterator, _InputIterator, const _Tp &)' against 'int'
    count(_InputIterator __first, _InputIterator __last, const _Tp& __value_) {
    ^
/root/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__bit_reference:313:1: note: candidate template ignored: could not match 'typename __bit_iterator<_Cp, _IsConst>::difference_type (__bit_iterator<_Cp, _IsConst>, __bit_iterator<_Cp, _IsConst>, const _Tp &)' against 'int'
count(__bit_iterator<_Cp, _IsConst> __first, __bit_iterator<_Cp, _IsConst> __last, const _Tp& __value_)
^*****************************************************************
how can i call this function and have it print out the array...void displayUsernames(string array[], int arraySize) {
//display user names in array
 cout << "user names in array: " << endl;
 for (int i = 0; i < arraySize; i++) {
  if (array[i] != "empty") {
   cout << array[i] << endl; }
To call the displayUsernames() function and have it print out the array, you can do the following:

Create an array of strings.
Initialize the array with the usernames that you want to print out.
Call the displayUsernames() function, passing in the array and its size as arguments.
Here is an example of how to do this:

C++
void displayUsernames(string array[], int arraySize);

int main() {
  string usernames[3] = {"Alice", "Bob", "Carol"};

  displayUsernames(usernames, 3);

  return 0;
}
Use code with caution. Learn more
Output:

user names in array:
Alice
Bob
Carol
The displayUsernames() function will iterate over the array and print out each username that is not empty.

Here is the function definition for displayUsernames():

C++
void displayUsernames(string array[], int arraySize) {
  cout << "user names in array: " << endl;
  for (int i = 0; i < arraySize; i++) {
    if (array[i] != "empty") {
      cout << array[i] << endl;
    }
  }
}
Use code with caution. Learn more
profile picture
why am i getting error: undefined symbol: for ....#include <iostream>
#include <string>

using namespace std;
void displayUsernames(string array[], int arraySize);

int main() {
 string usernames[3] = {"Alice", "Bob", "Carol"};

 displayUsernames(usernames, 3);

 return 0;
}
View other drafts



















You are getting the error "undefined symbol: for" because you have not compiled the displayUsernames() function. To compile the displayUsernames() function, you need to add it to the same file as your main() function, or to a separate file that is included in your program.

Once you have added the displayUsernames() function to your program, you need to compile it. To do this, you can use the following command:

g++ -o my_program my_program.cpp
This will compile your program into an executable file called my_program.

Once your program is compiled, you can run it using the following command:

./my_program
This will run your program and print out the usernames in the array.

Here is a complete example of your program that compiles and runs:

C++
#include <iostream>
#include <string>

using namespace std;

void displayUsernames(string array[], int arraySize);

int main() {
  string usernames[3] = {"Alice", "Bob", "Carol"};

  displayUsernames(usernames, 3);

  return 0;
}

void displayUsernames(string array[], int arraySize) {
  cout << "user names in array: " << endl;
  for (int i = 0; i < arraySize; i++) {
    cout << array[i] << endl;
  }
}
Use code with caution. Learn more
Output:

user names in array:
Alice
Bob
Carol